properties:
-
  id: 1
  name: 'Basement Midtown Plaza'
  location: 'Dublin'
  address1: 'Basement Midtown Plaza'
  address2: 'Cnr Bourke & Swanston Streets'
  address3: 'Melbourne'
  address4: '3000'
  country: 'Dublin'
  fax: '+353 1 804 9152'
  phone: '+353 1 804 9100'
  email: 'julen@visrez.com'
  checkin_checkout_details: 'reservation paid before stay'
  facilities_details: 'our hotel has many big and beautiful rooms, internet a wi-fi zone and a big kitchen for our customers'
  location_details: '5 minits walking from the bus station, and 10 minits by bus to the airport'
  cancellation_policy: '20'
  terms_and_conditions: 'you have to accept the text and conditions to go on'
  property_short_description: 'property near de beach'
  property_description: 'nice property near the beach, 5 minits walking to the city center'
  total_number_of_rooms: '30'
  total_number_of_beds: '95'
  max_bed_capacity: '100'
  property_code: '123'
  max_rooms_per_reservation: '5'
  shortcut: 'Midtown'
  google_map_code: ''
  url: 'www.basementmidtownplaza.com'
-
  id: 2
  name: 'Highpoint hotel'
  location: 'Santiago'
  address1: 'Highpoint Hotel'
  address2: '120-200 Rosamond Road'
  address3: 'Maribyrnong'
  address4: '35'
  country: 'Chile'
  fax: '+75 5 359 9422'
  phone: '+75 5 507 6598'
  email: 'morales0_00@hotmail.com'
  checkin_checkout_details: 'just paid with creditcard or visa'
  facilities_details: 'our hotel is great for little groups, and couples who want to enjoy our city'
  location_details: '10 minits walking from the bus station, and 30 minits by bus to the airport, youre in the city center'
  cancellation_policy: '10'
  terms_and_conditions: 'you have to accept the text and conditions to go on'
  property_short_description: 'the greatest hotel for a few days visiting our city'
  property_description: 'in the center, with lot of journeys to visit the country, our hotel is one of the best hotels of the city, with the best location and best accomodation, really confortable'
  total_number_of_rooms: '50'
  total_number_of_beds: '150'
  max_bed_capacity: '200'
  property_code: '954'
  max_rooms_per_reservation: '10'
  shortcut: 'Highpoint'
  google_map_code: ''
  url: 'www.Highpointhotel.com'
-
  id: 3
  name: 'Watergardens hotel'
  location: 'Dublin'
  address1: 'Watergardens Hotel'
  address2: '103 Donnycarney Rd'
  address3: 'Dublin 9'
  address4: '98'
  country: 'Dublin'
  fax: '+353 9 406 9792'
  phone: '+353 9 406 9793'
  email: 'julenkini@gmail.com'
  checkin_checkout_details: 'we accept all kind of reservation modes'
  facilities_details: 'very big and confortable rooms, ideal for stay in here long time, TV and internet in each room'
  location_details: '5 minits walking from the bus station, and 1 hour by bus to the airport'
  cancellation_policy: '50'
  terms_and_conditions: 'you have to accept the text and conditions to go on'
  property_short_description: 'luxurious hostel in a cheap prize'
  property_description: 'this hotel is the best one to stay long time in a cheap prize, with our luxurious system you would like to stay longer in here'
  total_number_of_rooms: 100'
  total_number_of_beds: '270'
  max_bed_capacity: '400'
  property_code: '991'
  max_rooms_per_reservation: '2'
  shortcut: 'Watergardens'
  google_map_code: ''
  url: 'www.watergardenshotel.com'