properties:
-
  id: 1
  name: 'Basement Midtown Plaza'
  location: 'Dublin'
  address1: 'Basement Midtown Plaza'
  address2: 'Cnr Bourke & Swanston Streets'
  address3: 'Melbourne'
  address4: '3000'
  country: 'Dublin'
  fax: '+353 1 804 9152'
  phone: '+353 1 804 9100'
  email: 'julen@visrez.com'
  checkin_checkout_details: 'reservation paid before stay'
  facilities_details: 'our hotel has many big and beautiful rooms, internet a wi-fi zone and a big kitchen for our customers'
  location_details: '5 minits walking from the bus station, and 10 minits by bus to the airport'
  cancellation_policy: '20'
  terms_and_conditions: 'you have to accept the text and conditions to go on'
  property_short_description: 'property near de beach'
  property_description: 'nice property near the beach, 5 minits walking to the city center'
  total_number_of_rooms: '30'
  total_number_of_beds: '95'
  max_bed_capacity: '100'
  property_code: '123'
  max_rooms_per_reservation: '5'
  shortcut: 'Midtown'
  google_map_code: ''
  url: 'www.basementmidtownplaza.com'
-
  id: 2
  name: 'Highpoint hotel'
  location: 'Santiago'
  address1: 'Highpoint Hotel'
  address2: '120-200 Rosamond Road'
  address3: 'Maribyrnong'
  address4: '35'
  country: 'Chile'
  fax: '+75 5 359 9422'
  phone: '+75 5 507 6598'
  email: 'morales0_00@hotmail.com'
  checkin_checkout_details: 'just paid with creditcard or visa'
  facilities_details: 'our hotel is great for little groups, and couples who want to enjoy our city'
  location_details: '10 minits walking from the bus station, and 30 minits by bus to the airport, youre in the city center'
  cancellation_policy: '10'
  terms_and_conditions: 'you have to accept the text and conditions to go on'
  property_short_description: 'the greatest hotel for a few days visiting our city'
  property_description: 'in the center, with lot of journeys to visit the country, our hotel is one of the best hotels of the city, with the best location and best accomodation, really confortable'
  total_number_of_rooms: '50'
  total_number_of_beds: '150'
  max_bed_capacity: '200'
  property_code: '954'
  max_rooms_per_reservation: '10'
  shortcut: 'Highpoint'
  google_map_code: ''
  url: 'www.Highpointhotel.com'
-
  id: 3
  name: 'Watergardens hotel'
  location: 'Dublin'
  address1: 'Watergardens Hotel'
  address2: '103 Donnycarney Rd'
  address3: 'Dublin 9'
  address4: '98'
  country: 'Dublin'
  fax: '+353 9 406 9792'
  phone: '+353 9 406 9793'
  email: 'julenkini@gmail.com'
  checkin_checkout_details: 'we accept all kind of reservation modes'
  facilities_details: 'very big and confortable rooms, ideal for stay in here long time, TV and internet in each room'
  location_details: '5 minits walking from the bus station, and 1 hour by bus to the airport'
  cancellation_policy: '50'
  terms_and_conditions: 'you have to accept the text and conditions to go on'
  property_short_description: 'luxurious hostel in a cheap prize'
  property_description: 'this hotel is the best one to stay long time in a cheap prize, with our luxurious system you would like to stay longer in here'
  total_number_of_rooms: 100'
  total_number_of_beds: '270'
  max_bed_capacity: '400'
  property_code: '991'
  max_rooms_per_reservation: '2'
  shortcut: 'Watergardens'
  google_map_code: ''
  url: 'www.watergardenshotel.com'

#--------------------------------------------
#                   Rates
#--------------------------------------------

rates:
-
  id: 1
  code: 'BMDSR'
  name: 'Standard Rate'
  description: 'This is a standard rate'
  property_id: 1
-
  id: 2
  code: 'BMDCR'
  name: 'Cheap Rate'
  description: 'This rate is for books cheaper than 20€'
  property_id: 1
-
  id: 3
  code: 'HHSR'
  name: 'Standard Rate'
  description: 'This is a standard rate'
  property_id: 2
-
  id: 4
  code: 'HHGR'
  name: 'Group Rate'
  description: 'This is a group rate'
  property_id: 2
-
  id: 5
  code: 'WHSR'
  name: 'Standard Rate'
  description: 'This is a standard rate'
  property_id: 3
-
  id: 6
  code: 'WHSpR'
  name: 'Special Rate'
  description: 'This is a special rate'
  property_id: 3
  
#--------------------------------------------
#                 Room Types 
#--------------------------------------------

room_types:
-
  id: 1
  name: 'Single Room'
  adults: 5
  children: 0
  min_adults: 1
  max_children: 0
  description: 'This is a single room'
  short_description: ''
  code: 'SR'
  type: ''
-
  id: 2
  name: '6 Bed Room'
  adults: 2
  children: 4
  min_adults: 1
  max_children: 5
  description: 'This is a 6 bed room for familys or groups'
  short_description: '6 bed room'
  code: 'SB'
  type: ''
-
  id: 3
  name: 'Express room'
  adults: 4
  children: 1
  min_adults: 1
  max_children: 8
  description: 'This is a room for just a day'
  short_description: 'one night room'
  code: 'EX'
  type: ''
-
  id: 4
  name: '20 Bed Room'
  adults: 6
  children: 6
  min_adults: 0
  max_children: 20
  description: 'This is a 20 bed room'
  short_description: '20Bed room'
  code: 'TW'
  type: ''
-
  id: 5
  name: 'Children Room'
  adults: 0
  children: 3
  min_adults: 0
  max_children: 15
  description: 'This room can be used just by children 5-16 years'
  short_description: 'this is a children room'
  code: 'CR'
  type: ''
-
  id: 6
  name: 'president suit'
  adults: 2
  children: 0
  min_adults: 1
  max_children: 0
  description: 'This is our best room with all kind of equipments'
  short_description: 'This is the suit'
  code: 'PS'
  type: ''
-
  id: 7
  name: 'Students room'
  adults: 6
  children: 0
  min_adults: 1
  max_children: 10
  description: 'This is a students room with 10 beds and badroom'
  short_description: 'students room'
  code: 'ST'
  type: ''
-
  id: 8
  name: 'jacuzzi room'
  adults: 1
  children: 1
  min_adults: 1
  max_children: 4
  description: 'We have a jacuzzi in this room for clients'
  short_description: 'jacuzzi room'
  code: 'JR'
  type: ''
-
  id: 9
  name: 'VIP room'
  adults: 3
  children: 0
  min_adults: 1
  max_children: 6
  description: 'This room is reserved for special customers with an invitation'
  short_description: 'VIP room for special clients'
  code: 'VR'
  type: ''
-
  id: 10
  name: 'Double room'
  adults: 2
  children: 2
  min_adults: 1
  max_children: 4
  description: 'This room has 4 beds and a badroom'
  short_description: 'double room'
  code: 'DR'
  type: ''

#--------------------------------------------
#             Rate room types
#--------------------------------------------

rate_room_types:
-
  id: 1
  rate_id: 1
  room_type_id: 1
  allocation: 10
  position: 0
-
  id: 2
  rate_id: 1
  room_type_id: 7
  allocation: 5
  position: 0
-
  id: 3
  rate_id: 2
  room_type_id: 5
  allocation: 2
  position: 0
-
  id: 4
  rate_id: 2
  room_type_id: 10
  allocation: 15
  position: 0
-
  id: 5
  rate_id: 3
  room_type_id: 2
  allocation: 12
  position: 0
-
  id: 6
  rate_id: 3
  room_type_id: 3
  allocation: 6
  position: 0
-
  id: 7
  rate_id: 4
  room_type_id: 6
  allocation: 4
  position: 0
-
  id: 8
  rate_id: 4
  room_type_id: 8
  allocation: 9
  position: 0
-
  id: 9
  rate_id: 5
  room_type_id: 1
  allocation: 8
  position: 0
-
  id: 10
  rate_id: 5
  room_type_id: 9
  allocation: 12
  position: 0
-
  id: 11
  rate_id: 6
  room_type_id: 5
  allocation: 7
  position: 0
-
  id: 12
  rate_id: 6
  room_type_id: 4
  allocation: 5
  position: 0
